[general]
import = ["~/.config/alacritty/themes/tokyo_night.toml"]

[window]
decorations = "Buttonless"
opacity = 1.0
blur = false
dynamic_padding = true
padding = { x = 5, y = 5 }

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Light" }
size = 12
