[general]
import = ["~/.config/alacritty/themes/tokyo_night.toml"]

[window]
decorations = "Buttonless"
opacity = 0.9
blur = true
dynamic_padding = true
padding = { x = 5, y = 5 }

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Light" }
size = 12

[cursor.style]
shape = "Beam"
blinking = "Off"

[cursor.vi_mode_style]
shape = "Block"
blinking = "Off"
