onboarding = false

[theme]
name = "terminal"

[theme.custom]
accent = "#7aa2f7"
panel_bg = "#1a1b26"
surface0 = "#33467c"
surface1 = "#414868"
surface_dim = "#15161e"
overlay0 = "#a9b1d6"
overlay1 = "#c0caf5"
text = "#c0caf5"
subtext0 = "#a9b1d6"
mauve = "#bb9af7"
green = "#1DBA9A"
yellow = "#e0af68"
red = "#f7768e"
blue = "#7aa2f7"
teal = "#32ADE6"
peach = "#e0af68"
